<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;

class AjaxController extends Controller {

    public function index(Request $request) {
        $ch = curl_init();
        $url = 'https://api.github.com/search/users?q='.$request->input('user');
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        $response = curl_exec($ch);
        curl_close($ch);
        //test data incase github api is not accessible from local
   /*    $response = '{
  "total_count": 8882,
  "incomplete_results": false,
  "items": [
    {
      "login": "taylor",
      "id": 26697,
      "avatar_url": "https://avatars1.githubusercontent.com/u/26697?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/taylor",
      "html_url": "https://github.com/taylor",
      "followers_url": "https://api.github.com/users/taylor/followers",
      "following_url": "https://api.github.com/users/taylor/following{/other_user}",
      "gists_url": "https://api.github.com/users/taylor/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/taylor/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/taylor/subscriptions",
      "organizations_url": "https://api.github.com/users/taylor/orgs",
      "repos_url": "https://api.github.com/users/taylor/repos",
      "events_url": "https://api.github.com/users/taylor/events{/privacy}",
      "received_events_url": "https://api.github.com/users/taylor/received_events",
      "type": "User",
      "site_admin": false,
      "score": 90.72887
    },
    {
      "login": "taylorotwell",
      "id": 463230,
      "avatar_url": "https://avatars3.githubusercontent.com/u/463230?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/taylorotwell",
      "html_url": "https://github.com/taylorotwell",
      "followers_url": "https://api.github.com/users/taylorotwell/followers",
      "following_url": "https://api.github.com/users/taylorotwell/following{/other_user}",
      "gists_url": "https://api.github.com/users/taylorotwell/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/taylorotwell/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/taylorotwell/subscriptions",
      "organizations_url": "https://api.github.com/users/taylorotwell/orgs",
      "repos_url": "https://api.github.com/users/taylorotwell/repos",
      "events_url": "https://api.github.com/users/taylorotwell/events{/privacy}",
      "received_events_url": "https://api.github.com/users/taylorotwell/received_events",
      "type": "User",
      "site_admin": false,
      "score": 57.185425
    },
    {
      "login": "defuse",
      "id": 4211072,
      "avatar_url": "https://avatars1.githubusercontent.com/u/4211072?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/defuse",
      "html_url": "https://github.com/defuse",
      "followers_url": "https://api.github.com/users/defuse/followers",
      "following_url": "https://api.github.com/users/defuse/following{/other_user}",
      "gists_url": "https://api.github.com/users/defuse/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/defuse/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/defuse/subscriptions",
      "organizations_url": "https://api.github.com/users/defuse/orgs",
      "repos_url": "https://api.github.com/users/defuse/repos",
      "events_url": "https://api.github.com/users/defuse/events{/privacy}",
      "received_events_url": "https://api.github.com/users/defuse/received_events",
      "type": "User",
      "site_admin": false,
      "score": 53.214893
    },
    {
      "login": "tfausak",
      "id": 408753,
      "avatar_url": "https://avatars1.githubusercontent.com/u/408753?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/tfausak",
      "html_url": "https://github.com/tfausak",
      "followers_url": "https://api.github.com/users/tfausak/followers",
      "following_url": "https://api.github.com/users/tfausak/following{/other_user}",
      "gists_url": "https://api.github.com/users/tfausak/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/tfausak/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/tfausak/subscriptions",
      "organizations_url": "https://api.github.com/users/tfausak/orgs",
      "repos_url": "https://api.github.com/users/tfausak/repos",
      "events_url": "https://api.github.com/users/tfausak/events{/privacy}",
      "received_events_url": "https://api.github.com/users/tfausak/received_events",
      "type": "User",
      "site_admin": false,
      "score": 42.938683
    },
    {
      "login": "speedmax",
      "id": 3823,
      "avatar_url": "https://avatars2.githubusercontent.com/u/3823?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/speedmax",
      "html_url": "https://github.com/speedmax",
      "followers_url": "https://api.github.com/users/speedmax/followers",
      "following_url": "https://api.github.com/users/speedmax/following{/other_user}",
      "gists_url": "https://api.github.com/users/speedmax/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/speedmax/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/speedmax/subscriptions",
      "organizations_url": "https://api.github.com/users/speedmax/orgs",
      "repos_url": "https://api.github.com/users/speedmax/repos",
      "events_url": "https://api.github.com/users/speedmax/events{/privacy}",
      "received_events_url": "https://api.github.com/users/speedmax/received_events",
      "type": "User",
      "site_admin": false,
      "score": 36.9808
    },
    {
      "login": "wanghetommy",
      "id": 486457,
      "avatar_url": "https://avatars2.githubusercontent.com/u/486457?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/wanghetommy",
      "html_url": "https://github.com/wanghetommy",
      "followers_url": "https://api.github.com/users/wanghetommy/followers",
      "following_url": "https://api.github.com/users/wanghetommy/following{/other_user}",
      "gists_url": "https://api.github.com/users/wanghetommy/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/wanghetommy/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/wanghetommy/subscriptions",
      "organizations_url": "https://api.github.com/users/wanghetommy/orgs",
      "repos_url": "https://api.github.com/users/wanghetommy/repos",
      "events_url": "https://api.github.com/users/wanghetommy/events{/privacy}",
      "received_events_url": "https://api.github.com/users/wanghetommy/received_events",
      "type": "User",
      "site_admin": false,
      "score": 31.679836
    },
    {
      "login": "tylrtrmbl",
      "id": 1058478,
      "avatar_url": "https://avatars3.githubusercontent.com/u/1058478?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/tylrtrmbl",
      "html_url": "https://github.com/tylrtrmbl",
      "followers_url": "https://api.github.com/users/tylrtrmbl/followers",
      "following_url": "https://api.github.com/users/tylrtrmbl/following{/other_user}",
      "gists_url": "https://api.github.com/users/tylrtrmbl/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/tylrtrmbl/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/tylrtrmbl/subscriptions",
      "organizations_url": "https://api.github.com/users/tylrtrmbl/orgs",
      "repos_url": "https://api.github.com/users/tylrtrmbl/repos",
      "events_url": "https://api.github.com/users/tylrtrmbl/events{/privacy}",
      "received_events_url": "https://api.github.com/users/tylrtrmbl/received_events",
      "type": "User",
      "site_admin": false,
      "score": 31.031534
    },
    {
      "login": "taylor224",
      "id": 1826405,
      "avatar_url": "https://avatars1.githubusercontent.com/u/1826405?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/taylor224",
      "html_url": "https://github.com/taylor224",
      "followers_url": "https://api.github.com/users/taylor224/followers",
      "following_url": "https://api.github.com/users/taylor224/following{/other_user}",
      "gists_url": "https://api.github.com/users/taylor224/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/taylor224/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/taylor224/subscriptions",
      "organizations_url": "https://api.github.com/users/taylor224/orgs",
      "repos_url": "https://api.github.com/users/taylor224/repos",
      "events_url": "https://api.github.com/users/taylor224/events{/privacy}",
      "received_events_url": "https://api.github.com/users/taylor224/received_events",
      "type": "User",
      "site_admin": false,
      "score": 29.029871
    },
    {
      "login": "buley",
      "id": 86985,
      "avatar_url": "https://avatars3.githubusercontent.com/u/86985?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/buley",
      "html_url": "https://github.com/buley",
      "followers_url": "https://api.github.com/users/buley/followers",
      "following_url": "https://api.github.com/users/buley/following{/other_user}",
      "gists_url": "https://api.github.com/users/buley/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/buley/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/buley/subscriptions",
      "organizations_url": "https://api.github.com/users/buley/orgs",
      "repos_url": "https://api.github.com/users/buley/repos",
      "events_url": "https://api.github.com/users/buley/events{/privacy}",
      "received_events_url": "https://api.github.com/users/buley/received_events",
      "type": "User",
      "site_admin": false,
      "score": 28.554546
    },
    {
      "login": "davetayls",
      "id": 151695,
      "avatar_url": "https://avatars2.githubusercontent.com/u/151695?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/davetayls",
      "html_url": "https://github.com/davetayls",
      "followers_url": "https://api.github.com/users/davetayls/followers",
      "following_url": "https://api.github.com/users/davetayls/following{/other_user}",
      "gists_url": "https://api.github.com/users/davetayls/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/davetayls/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/davetayls/subscriptions",
      "organizations_url": "https://api.github.com/users/davetayls/orgs",
      "repos_url": "https://api.github.com/users/davetayls/repos",
      "events_url": "https://api.github.com/users/davetayls/events{/privacy}",
      "received_events_url": "https://api.github.com/users/davetayls/received_events",
      "type": "User",
      "site_admin": false,
      "score": 28.289375
    },
    {
      "login": "CrazyGuy108",
      "id": 13547043,
      "avatar_url": "https://avatars1.githubusercontent.com/u/13547043?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/CrazyGuy108",
      "html_url": "https://github.com/CrazyGuy108",
      "followers_url": "https://api.github.com/users/CrazyGuy108/followers",
      "following_url": "https://api.github.com/users/CrazyGuy108/following{/other_user}",
      "gists_url": "https://api.github.com/users/CrazyGuy108/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/CrazyGuy108/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/CrazyGuy108/subscriptions",
      "organizations_url": "https://api.github.com/users/CrazyGuy108/orgs",
      "repos_url": "https://api.github.com/users/CrazyGuy108/repos",
      "events_url": "https://api.github.com/users/CrazyGuy108/events{/privacy}",
      "received_events_url": "https://api.github.com/users/CrazyGuy108/received_events",
      "type": "User",
      "site_admin": false,
      "score": 27.768768
    },
    {
      "login": "taylorbanks",
      "id": 190576,
      "avatar_url": "https://avatars1.githubusercontent.com/u/190576?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/taylorbanks",
      "html_url": "https://github.com/taylorbanks",
      "followers_url": "https://api.github.com/users/taylorbanks/followers",
      "following_url": "https://api.github.com/users/taylorbanks/following{/other_user}",
      "gists_url": "https://api.github.com/users/taylorbanks/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/taylorbanks/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/taylorbanks/subscriptions",
      "organizations_url": "https://api.github.com/users/taylorbanks/orgs",
      "repos_url": "https://api.github.com/users/taylorbanks/repos",
      "events_url": "https://api.github.com/users/taylorbanks/events{/privacy}",
      "received_events_url": "https://api.github.com/users/taylorbanks/received_events",
      "type": "User",
      "site_admin": false,
      "score": 27.731508
    },
    {
      "login": "TaylorRayHoward",
      "id": 10507313,
      "avatar_url": "https://avatars2.githubusercontent.com/u/10507313?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/TaylorRayHoward",
      "html_url": "https://github.com/TaylorRayHoward",
      "followers_url": "https://api.github.com/users/TaylorRayHoward/followers",
      "following_url": "https://api.github.com/users/TaylorRayHoward/following{/other_user}",
      "gists_url": "https://api.github.com/users/TaylorRayHoward/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/TaylorRayHoward/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/TaylorRayHoward/subscriptions",
      "organizations_url": "https://api.github.com/users/TaylorRayHoward/orgs",
      "repos_url": "https://api.github.com/users/TaylorRayHoward/repos",
      "events_url": "https://api.github.com/users/TaylorRayHoward/events{/privacy}",
      "received_events_url": "https://api.github.com/users/TaylorRayHoward/received_events",
      "type": "User",
      "site_admin": false,
      "score": 26.776236
    },
    {
      "login": "taylorchen709",
      "id": 11830960,
      "avatar_url": "https://avatars0.githubusercontent.com/u/11830960?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/taylorchen709",
      "html_url": "https://github.com/taylorchen709",
      "followers_url": "https://api.github.com/users/taylorchen709/followers",
      "following_url": "https://api.github.com/users/taylorchen709/following{/other_user}",
      "gists_url": "https://api.github.com/users/taylorchen709/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/taylorchen709/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/taylorchen709/subscriptions",
      "organizations_url": "https://api.github.com/users/taylorchen709/orgs",
      "repos_url": "https://api.github.com/users/taylorchen709/repos",
      "events_url": "https://api.github.com/users/taylorchen709/events{/privacy}",
      "received_events_url": "https://api.github.com/users/taylorchen709/received_events",
      "type": "User",
      "site_admin": false,
      "score": 26.462067
    },
    {
      "login": "nocnokneo",
      "id": 514960,
      "avatar_url": "https://avatars0.githubusercontent.com/u/514960?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/nocnokneo",
      "html_url": "https://github.com/nocnokneo",
      "followers_url": "https://api.github.com/users/nocnokneo/followers",
      "following_url": "https://api.github.com/users/nocnokneo/following{/other_user}",
      "gists_url": "https://api.github.com/users/nocnokneo/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/nocnokneo/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/nocnokneo/subscriptions",
      "organizations_url": "https://api.github.com/users/nocnokneo/orgs",
      "repos_url": "https://api.github.com/users/nocnokneo/repos",
      "events_url": "https://api.github.com/users/nocnokneo/events{/privacy}",
      "received_events_url": "https://api.github.com/users/nocnokneo/received_events",
      "type": "User",
      "site_admin": false,
      "score": 25.458597
    },
    {
      "login": "pourbrew",
      "id": 1881963,
      "avatar_url": "https://avatars3.githubusercontent.com/u/1881963?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/pourbrew",
      "html_url": "https://github.com/pourbrew",
      "followers_url": "https://api.github.com/users/pourbrew/followers",
      "following_url": "https://api.github.com/users/pourbrew/following{/other_user}",
      "gists_url": "https://api.github.com/users/pourbrew/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/pourbrew/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/pourbrew/subscriptions",
      "organizations_url": "https://api.github.com/users/pourbrew/orgs",
      "repos_url": "https://api.github.com/users/pourbrew/repos",
      "events_url": "https://api.github.com/users/pourbrew/events{/privacy}",
      "received_events_url": "https://api.github.com/users/pourbrew/received_events",
      "type": "User",
      "site_admin": false,
      "score": 25.321869
    },
    {
      "login": "brinkt",
      "id": 189861,
      "avatar_url": "https://avatars0.githubusercontent.com/u/189861?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/brinkt",
      "html_url": "https://github.com/brinkt",
      "followers_url": "https://api.github.com/users/brinkt/followers",
      "following_url": "https://api.github.com/users/brinkt/following{/other_user}",
      "gists_url": "https://api.github.com/users/brinkt/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/brinkt/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/brinkt/subscriptions",
      "organizations_url": "https://api.github.com/users/brinkt/orgs",
      "repos_url": "https://api.github.com/users/brinkt/repos",
      "events_url": "https://api.github.com/users/brinkt/events{/privacy}",
      "received_events_url": "https://api.github.com/users/brinkt/received_events",
      "type": "User",
      "site_admin": false,
      "score": 24.67771
    },
    {
      "login": "taylorbryant",
      "id": 3718939,
      "avatar_url": "https://avatars1.githubusercontent.com/u/3718939?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/taylorbryant",
      "html_url": "https://github.com/taylorbryant",
      "followers_url": "https://api.github.com/users/taylorbryant/followers",
      "following_url": "https://api.github.com/users/taylorbryant/following{/other_user}",
      "gists_url": "https://api.github.com/users/taylorbryant/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/taylorbryant/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/taylorbryant/subscriptions",
      "organizations_url": "https://api.github.com/users/taylorbryant/orgs",
      "repos_url": "https://api.github.com/users/taylorbryant/repos",
      "events_url": "https://api.github.com/users/taylorbryant/events{/privacy}",
      "received_events_url": "https://api.github.com/users/taylorbryant/received_events",
      "type": "User",
      "site_admin": false,
      "score": 24.62745
    },
    {
      "login": "statsmaths",
      "id": 5752184,
      "avatar_url": "https://avatars3.githubusercontent.com/u/5752184?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/statsmaths",
      "html_url": "https://github.com/statsmaths",
      "followers_url": "https://api.github.com/users/statsmaths/followers",
      "following_url": "https://api.github.com/users/statsmaths/following{/other_user}",
      "gists_url": "https://api.github.com/users/statsmaths/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/statsmaths/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/statsmaths/subscriptions",
      "organizations_url": "https://api.github.com/users/statsmaths/orgs",
      "repos_url": "https://api.github.com/users/statsmaths/repos",
      "events_url": "https://api.github.com/users/statsmaths/events{/privacy}",
      "received_events_url": "https://api.github.com/users/statsmaths/received_events",
      "type": "User",
      "site_admin": false,
      "score": 24.28131
    },
    {
      "login": "taylorhughes",
      "id": 907886,
      "avatar_url": "https://avatars2.githubusercontent.com/u/907886?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/taylorhughes",
      "html_url": "https://github.com/taylorhughes",
      "followers_url": "https://api.github.com/users/taylorhughes/followers",
      "following_url": "https://api.github.com/users/taylorhughes/following{/other_user}",
      "gists_url": "https://api.github.com/users/taylorhughes/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/taylorhughes/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/taylorhughes/subscriptions",
      "organizations_url": "https://api.github.com/users/taylorhughes/orgs",
      "repos_url": "https://api.github.com/users/taylorhughes/repos",
      "events_url": "https://api.github.com/users/taylorhughes/events{/privacy}",
      "received_events_url": "https://api.github.com/users/taylorhughes/received_events",
      "type": "User",
      "site_admin": false,
      "score": 24.095295
    },
    {
      "login": "miketaylr",
      "id": 67283,
      "avatar_url": "https://avatars1.githubusercontent.com/u/67283?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/miketaylr",
      "html_url": "https://github.com/miketaylr",
      "followers_url": "https://api.github.com/users/miketaylr/followers",
      "following_url": "https://api.github.com/users/miketaylr/following{/other_user}",
      "gists_url": "https://api.github.com/users/miketaylr/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/miketaylr/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/miketaylr/subscriptions",
      "organizations_url": "https://api.github.com/users/miketaylr/orgs",
      "repos_url": "https://api.github.com/users/miketaylr/repos",
      "events_url": "https://api.github.com/users/miketaylr/events{/privacy}",
      "received_events_url": "https://api.github.com/users/miketaylr/received_events",
      "type": "User",
      "site_admin": false,
      "score": 23.782808
    },
    {
      "login": "taylordowns2000",
      "id": 8732845,
      "avatar_url": "https://avatars2.githubusercontent.com/u/8732845?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/taylordowns2000",
      "html_url": "https://github.com/taylordowns2000",
      "followers_url": "https://api.github.com/users/taylordowns2000/followers",
      "following_url": "https://api.github.com/users/taylordowns2000/following{/other_user}",
      "gists_url": "https://api.github.com/users/taylordowns2000/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/taylordowns2000/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/taylordowns2000/subscriptions",
      "organizations_url": "https://api.github.com/users/taylordowns2000/orgs",
      "repos_url": "https://api.github.com/users/taylordowns2000/repos",
      "events_url": "https://api.github.com/users/taylordowns2000/events{/privacy}",
      "received_events_url": "https://api.github.com/users/taylordowns2000/received_events",
      "type": "User",
      "site_admin": false,
      "score": 23.77544
    },
    {
      "login": "trxcllnt",
      "id": 178183,
      "avatar_url": "https://avatars0.githubusercontent.com/u/178183?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/trxcllnt",
      "html_url": "https://github.com/trxcllnt",
      "followers_url": "https://api.github.com/users/trxcllnt/followers",
      "following_url": "https://api.github.com/users/trxcllnt/following{/other_user}",
      "gists_url": "https://api.github.com/users/trxcllnt/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/trxcllnt/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/trxcllnt/subscriptions",
      "organizations_url": "https://api.github.com/users/trxcllnt/orgs",
      "repos_url": "https://api.github.com/users/trxcllnt/repos",
      "events_url": "https://api.github.com/users/trxcllnt/events{/privacy}",
      "received_events_url": "https://api.github.com/users/trxcllnt/received_events",
      "type": "User",
      "site_admin": false,
      "score": 22.772154
    },
    {
      "login": "tmcgann",
      "id": 1307188,
      "avatar_url": "https://avatars1.githubusercontent.com/u/1307188?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/tmcgann",
      "html_url": "https://github.com/tmcgann",
      "followers_url": "https://api.github.com/users/tmcgann/followers",
      "following_url": "https://api.github.com/users/tmcgann/following{/other_user}",
      "gists_url": "https://api.github.com/users/tmcgann/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/tmcgann/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/tmcgann/subscriptions",
      "organizations_url": "https://api.github.com/users/tmcgann/orgs",
      "repos_url": "https://api.github.com/users/tmcgann/repos",
      "events_url": "https://api.github.com/users/tmcgann/events{/privacy}",
      "received_events_url": "https://api.github.com/users/tmcgann/received_events",
      "type": "User",
      "site_admin": false,
      "score": 22.516138
    },
    {
      "login": "whotooktwarden",
      "id": 5444589,
      "avatar_url": "https://avatars2.githubusercontent.com/u/5444589?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/whotooktwarden",
      "html_url": "https://github.com/whotooktwarden",
      "followers_url": "https://api.github.com/users/whotooktwarden/followers",
      "following_url": "https://api.github.com/users/whotooktwarden/following{/other_user}",
      "gists_url": "https://api.github.com/users/whotooktwarden/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/whotooktwarden/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/whotooktwarden/subscriptions",
      "organizations_url": "https://api.github.com/users/whotooktwarden/orgs",
      "repos_url": "https://api.github.com/users/whotooktwarden/repos",
      "events_url": "https://api.github.com/users/whotooktwarden/events{/privacy}",
      "received_events_url": "https://api.github.com/users/whotooktwarden/received_events",
      "type": "User",
      "site_admin": false,
      "score": 22.495975
    },
    {
      "login": "austintaylor",
      "id": 9051,
      "avatar_url": "https://avatars1.githubusercontent.com/u/9051?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/austintaylor",
      "html_url": "https://github.com/austintaylor",
      "followers_url": "https://api.github.com/users/austintaylor/followers",
      "following_url": "https://api.github.com/users/austintaylor/following{/other_user}",
      "gists_url": "https://api.github.com/users/austintaylor/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/austintaylor/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/austintaylor/subscriptions",
      "organizations_url": "https://api.github.com/users/austintaylor/orgs",
      "repos_url": "https://api.github.com/users/austintaylor/repos",
      "events_url": "https://api.github.com/users/austintaylor/events{/privacy}",
      "received_events_url": "https://api.github.com/users/austintaylor/received_events",
      "type": "User",
      "site_admin": false,
      "score": 22.392187
    },
    {
      "login": "smtlaissezfaire",
      "id": 3690,
      "avatar_url": "https://avatars0.githubusercontent.com/u/3690?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/smtlaissezfaire",
      "html_url": "https://github.com/smtlaissezfaire",
      "followers_url": "https://api.github.com/users/smtlaissezfaire/followers",
      "following_url": "https://api.github.com/users/smtlaissezfaire/following{/other_user}",
      "gists_url": "https://api.github.com/users/smtlaissezfaire/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/smtlaissezfaire/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/smtlaissezfaire/subscriptions",
      "organizations_url": "https://api.github.com/users/smtlaissezfaire/orgs",
      "repos_url": "https://api.github.com/users/smtlaissezfaire/repos",
      "events_url": "https://api.github.com/users/smtlaissezfaire/events{/privacy}",
      "received_events_url": "https://api.github.com/users/smtlaissezfaire/received_events",
      "type": "User",
      "site_admin": false,
      "score": 22.386211
    },
    {
      "login": "taylorkpotter",
      "id": 761130,
      "avatar_url": "https://avatars0.githubusercontent.com/u/761130?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/taylorkpotter",
      "html_url": "https://github.com/taylorkpotter",
      "followers_url": "https://api.github.com/users/taylorkpotter/followers",
      "following_url": "https://api.github.com/users/taylorkpotter/following{/other_user}",
      "gists_url": "https://api.github.com/users/taylorkpotter/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/taylorkpotter/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/taylorkpotter/subscriptions",
      "organizations_url": "https://api.github.com/users/taylorkpotter/orgs",
      "repos_url": "https://api.github.com/users/taylorkpotter/repos",
      "events_url": "https://api.github.com/users/taylorkpotter/events{/privacy}",
      "received_events_url": "https://api.github.com/users/taylorkpotter/received_events",
      "type": "User",
      "site_admin": false,
      "score": 22.283258
    },
    {
      "login": "kragniz",
      "id": 735008,
      "avatar_url": "https://avatars2.githubusercontent.com/u/735008?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kragniz",
      "html_url": "https://github.com/kragniz",
      "followers_url": "https://api.github.com/users/kragniz/followers",
      "following_url": "https://api.github.com/users/kragniz/following{/other_user}",
      "gists_url": "https://api.github.com/users/kragniz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kragniz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kragniz/subscriptions",
      "organizations_url": "https://api.github.com/users/kragniz/orgs",
      "repos_url": "https://api.github.com/users/kragniz/repos",
      "events_url": "https://api.github.com/users/kragniz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kragniz/received_events",
      "type": "User",
      "site_admin": false,
      "score": 22.212912
    },
    {
      "login": "liquidg3",
      "id": 2308747,
      "avatar_url": "https://avatars0.githubusercontent.com/u/2308747?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/liquidg3",
      "html_url": "https://github.com/liquidg3",
      "followers_url": "https://api.github.com/users/liquidg3/followers",
      "following_url": "https://api.github.com/users/liquidg3/following{/other_user}",
      "gists_url": "https://api.github.com/users/liquidg3/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/liquidg3/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/liquidg3/subscriptions",
      "organizations_url": "https://api.github.com/users/liquidg3/orgs",
      "repos_url": "https://api.github.com/users/liquidg3/repos",
      "events_url": "https://api.github.com/users/liquidg3/events{/privacy}",
      "received_events_url": "https://api.github.com/users/liquidg3/received_events",
      "type": "User",
      "site_admin": false,
      "score": 22.195696
    }
  ]
}'; */
        return response($response);
    }
    
    public function followers(Request $request) {
        $ch = curl_init();
        $url = 'https://api.github.com/users/'.$request->input('user').'/followers?per_page=5&page='.$request->input('page');
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        $response = curl_exec($ch);
        curl_close($ch);
     /*   $response = '[
  {
    "login": "baldrailers",
    "id": 53907,
    "avatar_url": "https://avatars1.githubusercontent.com/u/53907?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/baldrailers",
    "html_url": "https://github.com/baldrailers",
    "followers_url": "https://api.github.com/users/baldrailers/followers",
    "following_url": "https://api.github.com/users/baldrailers/following{/other_user}",
    "gists_url": "https://api.github.com/users/baldrailers/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/baldrailers/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/baldrailers/subscriptions",
    "organizations_url": "https://api.github.com/users/baldrailers/orgs",
    "repos_url": "https://api.github.com/users/baldrailers/repos",
    "events_url": "https://api.github.com/users/baldrailers/events{/privacy}",
    "received_events_url": "https://api.github.com/users/baldrailers/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "sfgeorge",
    "id": 208529,
    "avatar_url": "https://avatars2.githubusercontent.com/u/208529?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/sfgeorge",
    "html_url": "https://github.com/sfgeorge",
    "followers_url": "https://api.github.com/users/sfgeorge/followers",
    "following_url": "https://api.github.com/users/sfgeorge/following{/other_user}",
    "gists_url": "https://api.github.com/users/sfgeorge/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/sfgeorge/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/sfgeorge/subscriptions",
    "organizations_url": "https://api.github.com/users/sfgeorge/orgs",
    "repos_url": "https://api.github.com/users/sfgeorge/repos",
    "events_url": "https://api.github.com/users/sfgeorge/events{/privacy}",
    "received_events_url": "https://api.github.com/users/sfgeorge/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "benlangfeld",
    "id": 210221,
    "avatar_url": "https://avatars3.githubusercontent.com/u/210221?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/benlangfeld",
    "html_url": "https://github.com/benlangfeld",
    "followers_url": "https://api.github.com/users/benlangfeld/followers",
    "following_url": "https://api.github.com/users/benlangfeld/following{/other_user}",
    "gists_url": "https://api.github.com/users/benlangfeld/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/benlangfeld/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/benlangfeld/subscriptions",
    "organizations_url": "https://api.github.com/users/benlangfeld/orgs",
    "repos_url": "https://api.github.com/users/benlangfeld/repos",
    "events_url": "https://api.github.com/users/benlangfeld/events{/privacy}",
    "received_events_url": "https://api.github.com/users/benlangfeld/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "kingbin",
    "id": 221555,
    "avatar_url": "https://avatars2.githubusercontent.com/u/221555?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/kingbin",
    "html_url": "https://github.com/kingbin",
    "followers_url": "https://api.github.com/users/kingbin/followers",
    "following_url": "https://api.github.com/users/kingbin/following{/other_user}",
    "gists_url": "https://api.github.com/users/kingbin/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/kingbin/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/kingbin/subscriptions",
    "organizations_url": "https://api.github.com/users/kingbin/orgs",
    "repos_url": "https://api.github.com/users/kingbin/repos",
    "events_url": "https://api.github.com/users/kingbin/events{/privacy}",
    "received_events_url": "https://api.github.com/users/kingbin/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "eric-wood",
    "id": 275624,
    "avatar_url": "https://avatars2.githubusercontent.com/u/275624?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/eric-wood",
    "html_url": "https://github.com/eric-wood",
    "followers_url": "https://api.github.com/users/eric-wood/followers",
    "following_url": "https://api.github.com/users/eric-wood/following{/other_user}",
    "gists_url": "https://api.github.com/users/eric-wood/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/eric-wood/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/eric-wood/subscriptions",
    "organizations_url": "https://api.github.com/users/eric-wood/orgs",
    "repos_url": "https://api.github.com/users/eric-wood/repos",
    "events_url": "https://api.github.com/users/eric-wood/events{/privacy}",
    "received_events_url": "https://api.github.com/users/eric-wood/received_events",
    "type": "User",
    "site_admin": false
  }
]';*/
        
        
        return response($response);
    }

}
